### ISSUE TITLE
Add support for the web?

### ISSUE THREAD

**Issue by jaredsburrows** [aaassseee/screen_brightness#6]
Add support for mobile web?

**Comment by aaassseee** [comment]
No, there will never be happen. Due to webview cannot access user device as far as I know. So mobile web support is actually impossible to be done. Or any information which can make this work?
Reference: [https://stackoverflow.com/questions/62545271/temporarily-increase-screen-brightness-in-android-webview](https://stackoverflow.com/questions/62545271/temporarily-increase-screen-brightness-in-android-webview)
